[package]
name = "iiot-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paho-mqtt = "0.13.3"
rand = "0.9.1"
actix-web = "4.11.0"
